/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.pbccrc.zsls.api.thrift.records;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-4-6")
public class HeartBeatRequest implements org.apache.thrift.TBase<HeartBeatRequest, HeartBeatRequest._Fields>, java.io.Serializable, Cloneable, Comparable<HeartBeatRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HeartBeatRequest");

  private static final org.apache.thrift.protocol.TField DOMAIN_FIELD_DESC = new org.apache.thrift.protocol.TField("domain", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NODEID_FIELD_DESC = new org.apache.thrift.protocol.TField("nodeid", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField RUNNING_TASKS_FIELD_DESC = new org.apache.thrift.protocol.TField("runningTasks", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HeartBeatRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HeartBeatRequestTupleSchemeFactory());
  }

  public String domain; // required
  public TNodeId nodeid; // required
  public List<TTaskId> runningTasks; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DOMAIN((short)1, "domain"),
    NODEID((short)2, "nodeid"),
    RUNNING_TASKS((short)3, "runningTasks");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DOMAIN
          return DOMAIN;
        case 2: // NODEID
          return NODEID;
        case 3: // RUNNING_TASKS
          return RUNNING_TASKS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DOMAIN, new org.apache.thrift.meta_data.FieldMetaData("domain", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NODEID, new org.apache.thrift.meta_data.FieldMetaData("nodeid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TNodeId.class)));
    tmpMap.put(_Fields.RUNNING_TASKS, new org.apache.thrift.meta_data.FieldMetaData("runningTasks", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TTaskId.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HeartBeatRequest.class, metaDataMap);
  }

  public HeartBeatRequest() {
  }

  public HeartBeatRequest(
    String domain,
    TNodeId nodeid,
    List<TTaskId> runningTasks)
  {
    this();
    this.domain = domain;
    this.nodeid = nodeid;
    this.runningTasks = runningTasks;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HeartBeatRequest(HeartBeatRequest other) {
    if (other.isSetDomain()) {
      this.domain = other.domain;
    }
    if (other.isSetNodeid()) {
      this.nodeid = new TNodeId(other.nodeid);
    }
    if (other.isSetRunningTasks()) {
      List<TTaskId> __this__runningTasks = new ArrayList<TTaskId>(other.runningTasks.size());
      for (TTaskId other_element : other.runningTasks) {
        __this__runningTasks.add(new TTaskId(other_element));
      }
      this.runningTasks = __this__runningTasks;
    }
  }

  public HeartBeatRequest deepCopy() {
    return new HeartBeatRequest(this);
  }

  @Override
  public void clear() {
    this.domain = null;
    this.nodeid = null;
    this.runningTasks = null;
  }

  public String getDomain() {
    return this.domain;
  }

  public HeartBeatRequest setDomain(String domain) {
    this.domain = domain;
    return this;
  }

  public void unsetDomain() {
    this.domain = null;
  }

  /** Returns true if field domain is set (has been assigned a value) and false otherwise */
  public boolean isSetDomain() {
    return this.domain != null;
  }

  public void setDomainIsSet(boolean value) {
    if (!value) {
      this.domain = null;
    }
  }

  public TNodeId getNodeid() {
    return this.nodeid;
  }

  public HeartBeatRequest setNodeid(TNodeId nodeid) {
    this.nodeid = nodeid;
    return this;
  }

  public void unsetNodeid() {
    this.nodeid = null;
  }

  /** Returns true if field nodeid is set (has been assigned a value) and false otherwise */
  public boolean isSetNodeid() {
    return this.nodeid != null;
  }

  public void setNodeidIsSet(boolean value) {
    if (!value) {
      this.nodeid = null;
    }
  }

  public int getRunningTasksSize() {
    return (this.runningTasks == null) ? 0 : this.runningTasks.size();
  }

  public java.util.Iterator<TTaskId> getRunningTasksIterator() {
    return (this.runningTasks == null) ? null : this.runningTasks.iterator();
  }

  public void addToRunningTasks(TTaskId elem) {
    if (this.runningTasks == null) {
      this.runningTasks = new ArrayList<TTaskId>();
    }
    this.runningTasks.add(elem);
  }

  public List<TTaskId> getRunningTasks() {
    return this.runningTasks;
  }

  public HeartBeatRequest setRunningTasks(List<TTaskId> runningTasks) {
    this.runningTasks = runningTasks;
    return this;
  }

  public void unsetRunningTasks() {
    this.runningTasks = null;
  }

  /** Returns true if field runningTasks is set (has been assigned a value) and false otherwise */
  public boolean isSetRunningTasks() {
    return this.runningTasks != null;
  }

  public void setRunningTasksIsSet(boolean value) {
    if (!value) {
      this.runningTasks = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DOMAIN:
      if (value == null) {
        unsetDomain();
      } else {
        setDomain((String)value);
      }
      break;

    case NODEID:
      if (value == null) {
        unsetNodeid();
      } else {
        setNodeid((TNodeId)value);
      }
      break;

    case RUNNING_TASKS:
      if (value == null) {
        unsetRunningTasks();
      } else {
        setRunningTasks((List<TTaskId>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DOMAIN:
      return getDomain();

    case NODEID:
      return getNodeid();

    case RUNNING_TASKS:
      return getRunningTasks();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DOMAIN:
      return isSetDomain();
    case NODEID:
      return isSetNodeid();
    case RUNNING_TASKS:
      return isSetRunningTasks();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HeartBeatRequest)
      return this.equals((HeartBeatRequest)that);
    return false;
  }

  public boolean equals(HeartBeatRequest that) {
    if (that == null)
      return false;

    boolean this_present_domain = true && this.isSetDomain();
    boolean that_present_domain = true && that.isSetDomain();
    if (this_present_domain || that_present_domain) {
      if (!(this_present_domain && that_present_domain))
        return false;
      if (!this.domain.equals(that.domain))
        return false;
    }

    boolean this_present_nodeid = true && this.isSetNodeid();
    boolean that_present_nodeid = true && that.isSetNodeid();
    if (this_present_nodeid || that_present_nodeid) {
      if (!(this_present_nodeid && that_present_nodeid))
        return false;
      if (!this.nodeid.equals(that.nodeid))
        return false;
    }

    boolean this_present_runningTasks = true && this.isSetRunningTasks();
    boolean that_present_runningTasks = true && that.isSetRunningTasks();
    if (this_present_runningTasks || that_present_runningTasks) {
      if (!(this_present_runningTasks && that_present_runningTasks))
        return false;
      if (!this.runningTasks.equals(that.runningTasks))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_domain = true && (isSetDomain());
    list.add(present_domain);
    if (present_domain)
      list.add(domain);

    boolean present_nodeid = true && (isSetNodeid());
    list.add(present_nodeid);
    if (present_nodeid)
      list.add(nodeid);

    boolean present_runningTasks = true && (isSetRunningTasks());
    list.add(present_runningTasks);
    if (present_runningTasks)
      list.add(runningTasks);

    return list.hashCode();
  }

  @Override
  public int compareTo(HeartBeatRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDomain()).compareTo(other.isSetDomain());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDomain()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.domain, other.domain);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNodeid()).compareTo(other.isSetNodeid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNodeid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nodeid, other.nodeid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRunningTasks()).compareTo(other.isSetRunningTasks());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRunningTasks()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.runningTasks, other.runningTasks);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HeartBeatRequest(");
    boolean first = true;

    sb.append("domain:");
    if (this.domain == null) {
      sb.append("null");
    } else {
      sb.append(this.domain);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nodeid:");
    if (this.nodeid == null) {
      sb.append("null");
    } else {
      sb.append(this.nodeid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("runningTasks:");
    if (this.runningTasks == null) {
      sb.append("null");
    } else {
      sb.append(this.runningTasks);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (domain == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'domain' was not present! Struct: " + toString());
    }
    if (nodeid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'nodeid' was not present! Struct: " + toString());
    }
    if (runningTasks == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'runningTasks' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (nodeid != null) {
      nodeid.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HeartBeatRequestStandardSchemeFactory implements SchemeFactory {
    public HeartBeatRequestStandardScheme getScheme() {
      return new HeartBeatRequestStandardScheme();
    }
  }

  private static class HeartBeatRequestStandardScheme extends StandardScheme<HeartBeatRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HeartBeatRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DOMAIN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.domain = iprot.readString();
              struct.setDomainIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NODEID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.nodeid = new TNodeId();
              struct.nodeid.read(iprot);
              struct.setNodeidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RUNNING_TASKS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list36 = iprot.readListBegin();
                struct.runningTasks = new ArrayList<TTaskId>(_list36.size);
                TTaskId _elem37;
                for (int _i38 = 0; _i38 < _list36.size; ++_i38)
                {
                  _elem37 = new TTaskId();
                  _elem37.read(iprot);
                  struct.runningTasks.add(_elem37);
                }
                iprot.readListEnd();
              }
              struct.setRunningTasksIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HeartBeatRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.domain != null) {
        oprot.writeFieldBegin(DOMAIN_FIELD_DESC);
        oprot.writeString(struct.domain);
        oprot.writeFieldEnd();
      }
      if (struct.nodeid != null) {
        oprot.writeFieldBegin(NODEID_FIELD_DESC);
        struct.nodeid.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.runningTasks != null) {
        oprot.writeFieldBegin(RUNNING_TASKS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.runningTasks.size()));
          for (TTaskId _iter39 : struct.runningTasks)
          {
            _iter39.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HeartBeatRequestTupleSchemeFactory implements SchemeFactory {
    public HeartBeatRequestTupleScheme getScheme() {
      return new HeartBeatRequestTupleScheme();
    }
  }

  private static class HeartBeatRequestTupleScheme extends TupleScheme<HeartBeatRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HeartBeatRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.domain);
      struct.nodeid.write(oprot);
      {
        oprot.writeI32(struct.runningTasks.size());
        for (TTaskId _iter40 : struct.runningTasks)
        {
          _iter40.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HeartBeatRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.domain = iprot.readString();
      struct.setDomainIsSet(true);
      struct.nodeid = new TNodeId();
      struct.nodeid.read(iprot);
      struct.setNodeidIsSet(true);
      {
        org.apache.thrift.protocol.TList _list41 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.runningTasks = new ArrayList<TTaskId>(_list41.size);
        TTaskId _elem42;
        for (int _i43 = 0; _i43 < _list41.size; ++_i43)
        {
          _elem42 = new TTaskId();
          _elem42.read(iprot);
          struct.runningTasks.add(_elem42);
        }
      }
      struct.setRunningTasksIsSet(true);
    }
  }

}

