/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.pbccrc.zsls.api.thrift.records;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TaskAction implements org.apache.thrift.TEnum {
  COMPLETE(0),
  FAILED(1),
  QUARTZ_COMPLETE(2),
  QuARTZ_FAILED(3),
  ACCEPT(4),
  DENIED(5);

  private final int value;

  private TaskAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TaskAction findByValue(int value) { 
    switch (value) {
      case 0:
        return COMPLETE;
      case 1:
        return FAILED;
      case 2:
        return QUARTZ_COMPLETE;
      case 3:
        return QuARTZ_FAILED;
      case 4:
        return ACCEPT;
      case 5:
        return DENIED;
      default:
        return null;
    }
  }
}
