CREATE TABLE IF NOT EXISTS `UNITS_{tableName}` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`SWIFTNUM` VARCHAR(20),
	`PREUNIT` BIGINT(20) NOT NULL DEFAULT '-1',
	`JSONCONTENT` TEXT NOT NULL COLLATE 'utf8_bin',
	`STATUS` INT(11) NOT NULL DEFAULT '0',
	`TASKNUM` INT(11) NOT NULL DEFAULT '0',
	`CREATETIME` DATETIME NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB;