CREATE TABLE IF NOT EXISTS `QUARTZ_TASKS` (
	`TASKID` VARCHAR(20) NOT NULL COLLATE 'utf8_bin',
	`STAT` INT(11) NOT NULL DEFAULT '0',
	`JOBID` VARCHAR(24) NOT NULL ,
	`RESULT` VARCHAR(500) COLLATE 'utf8_bin',
	`RUNTIME_META` VARCHAR(512),
	`EXETIME` DATETIME NOT NULL
)
COLLATE='utf8_bin'
ENGINE=InnoDB;