CREATE TABLE TASKS_{tableName} (
	TASKID VARCHAR2(50) NOT NULL UNIQUE,
	STATUS NUMBER(11) DEFAULT 0 NOT NULL,
	UNITID VARCHAR2(50) NOT NULL,
	INFO VARCHAR2(4000),
	CNT NUMBER(11) DEFAULT 0 NOT NULL
)
